[namespace]
name = "dufeutech"
registry = "ghcr.io/dufeutech"

# dufeutech/mik-sdk
[[interface]]
name = "mik-sdk-wit"
repository = "mik-sdk-wit"

[[component]]
name = "mik-sdk-bridge"
repository = "mik-sdk-bridge"
