[namespace]
name = "jamesstocktonj1"
registry = "ghcr.io/jamesstocktonj1"

# jamesstocktonj1/ticker-provider - WIT
[[interface]]
name = "ticker-provider"
repository = "ticker-provider"

# jamesstocktonj1/componentize-sdk
[[component]]
name = "componentize-sdk"
repository = "componentize-sdk"
