[namespace]
name = "wasmcloud"
registry = "ghcr.io/wasmcloud"

# wasmCloud/wasmCloud - example components
[[component]]
name = "hello-world"
repository = "components/hello-world"

# wasmCloud/go - WIT interface
[[interface]]
name = "go-component-wit"
repository = "go/component-wit"
