use std::path::{Path, PathBuf};

use wasm_manifest::Lockfile;

/// Options for the `init` command.
#[derive(clap::Parser)]
pub(crate) struct Opts {
    /// The directory in which to create the wasm package files.
    ///
    /// Defaults to the current directory.
    #[arg(default_value = ".")]
    path: PathBuf,
}

impl Opts {
    pub(crate) async fn run(self) -> anyhow::Result<()> {
        let base = &self.path;
        let deps = base.join("deps");

        tokio::fs::create_dir_all(deps.join("vendor/wit")).await?;
        tokio::fs::create_dir_all(deps.join("vendor/wasm")).await?;

        let manifest = wasm_manifest::Manifest::default();
        let manifest = toml::to_string_pretty(&manifest)?;
        tokio::fs::write(deps.join("wasm.toml"), manifest.as_bytes()).await?;

        let lockfile = wasm_manifest::Lockfile::default();
        write_lock_file(deps.join("wasm.lock.toml"), &lockfile).await?;

        Ok(())
    }
}

async fn write_lock_file<P: AsRef<Path>>(path: P, lock: &Lockfile) -> std::io::Result<()> {
    let header = "# This file is automatically generated by wasm(1).\n\
                  # It should not be manually edited.\n";
    let body = toml::to_string_pretty(lock).expect("failed to serialize lock file");
    let contents = format!("{header}\n{body}");
    tokio::fs::write(path.as_ref(), contents).await
}
